<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="utf-8" />';
echo '<title>Konsultasi Psikologi Online Pusat Layanan Psikologi Jayabaya</title>';
echo '<meta content="width=device-width, initial-scale=1.0" name="viewport" />';
echo '<meta content="" name="keywords" />';
echo '<meta content="" name="description" />';
echo '';
echo '<!-- Favicon -->';
echo '<link href="img/ikon.ico" rel="icon" />';
echo '';
echo '<!-- Google Web Fonts -->';
echo '<link rel="preconnect" href="https://fonts.googleapis.com" />';
echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />';
echo '<link';
echo 'href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500&family=Jost:wght@500;600;700&display=swap"';
echo 'rel="stylesheet"';
echo '/>';
echo '';
echo '<!-- Icon Font Stylesheet -->';
echo '<link';
echo 'href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"';
echo 'rel="stylesheet"';
echo '/>';
echo '<link';
echo 'href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"';
echo 'rel="stylesheet"';
echo '/>';
echo '';
echo '<!-- Libraries Stylesheet -->';
echo '<link href="lib/animate/animate.min.css" rel="stylesheet" />';
echo '<link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />';
echo '<link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet" />';
echo '';
echo '<!-- Customized Bootstrap Stylesheet -->';
echo '<link href="css/bootstrap.min.css" rel="stylesheet" />';
echo '';
echo '<!-- Template Stylesheet -->';
echo '<link href="css/style.css" rel="stylesheet" />';
echo '</head>';
echo '';
echo '<body>';
echo '<div class="container-xxl bg-white p-0">';
echo '<!-- Spinner Start -->';
echo '<div';
echo 'id="spinner"';
echo 'class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center"';
echo '>';
echo '<div';
echo 'class="spinner-grow text-primary"';
echo 'style="width: 3rem; height: 3rem"';
echo 'role="status"';
echo '>';
echo '<span class="sr-only">Loading...</span>';
echo '</div>';
echo '</div>';
echo '<!-- Spinner End -->';
echo '';
echo '<!-- Navbar & Hero Start -->';
echo '<div class="container-xxl position-relative p-0">';
echo '<nav';
echo 'class="navbar navbar-expand-lg navbar-light px-4 px-lg-5 py-3 py-lg-0"';
echo '>';
echo '<a href="" class="navbar-brand p-0">';
echo '<img src="img/logo.png" alt="Logo" />';
echo '</a>';
echo '<button';
echo 'class="navbar-toggler"';
echo 'type="button"';
echo 'data-bs-toggle="collapse"';
echo 'data-bs-target="#navbarCollapse"';
echo '>';
echo '<span class="fa fa-bars"></span>';
echo '</button>';
echo '<div class="collapse navbar-collapse" id="navbarCollapse">';
echo '<div class="navbar-nav mx-auto py-0">';
echo '<a href="index.html" class="nav-item nav-link active">Home</a>';
echo '<a href="about.html" class="nav-item nav-link">About</a>';
echo '<a href="service.html" class="nav-item nav-link">Service</a>';
echo '<a href="booking.html" class="nav-item nav-link">Booking</a>';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '';
echo '<div class="container-xxl bg-primary hero-header">';
echo '<div class="container px-lg-5">';
echo '<div class="row g-5 align-items-end">';
echo '<div class="col-lg-6 text-center text-lg-start">';
echo '<h1 class="text-white mb-4 animated slideInDown">';
echo 'Online Phsycology Consultation';
echo '</h1>';
echo '<p class="text-white pb-3 animated slideInDown">';
echo 'Konsultasi psikologi adalah layanan kesehatan yang bertujuan';
echo 'untuk membantu seseorang mendapatkan bantuan dalam mengatasi';
echo 'masalah psikologis yang sedang dihadapi. Konsultasi psikologi';
echo 'berfokus pada kesehatan mental seseorang agar dapat';
echo 'menjalankan kehidupannya dengan baik dan memiliki relasi';
echo 'sosial yang baik.';
echo '</p>';
echo '<a';
echo 'href="about.html"';
echo 'class="btn btn-secondary py-sm-3 px-sm-5 rounded-pill me-3 animated slideInLeft"';
echo '>Read More</a';
echo '>';
echo '<a';
echo 'href="https://wa.link/ycqi7v"';
echo 'class="btn btn-light py-sm-3 px-sm-5 rounded-pill animated slideInRight"';
echo '>Contact Us</a';
echo '>';
echo '</div>';
echo '<div class="col-lg-6 text-center text-lg-start">';
echo '<img';
echo 'class="img-fluid animated zoomIn"';
echo 'src="img/konsul.png"';
echo 'alt=""';
echo 'style="border-radius: 1cm"';
echo '/>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Navbar & Hero End -->';
echo '';
echo '<!-- About Start -->';
echo '<div class="container-xxl py-5">';
echo '<div class="container py-5 px-lg-5">';
echo '<div class="row g-5 align-items-center">';
echo '<div class="col-lg-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<p class="section-title text-secondary">About Us<span></span></p>';
echo '<h1 class="mb-5">';
echo 'Kegiatan komunikasi dua arah antara pasien dan psikolog';
echo '</h1>';
echo '<p class="mb-4">';
echo 'Pusat Layanan Psikologi Jayabaya mengutamakan pertumbuhan dan';
echo 'perkembangan pribadi sehat untuk membantu individu';
echo 'mengoptimalkan potensi pada semua sisi kehidupannya. Membantu';
echo 'klien menemukan dan mengembangkan bakat dan potensi terbaik';
echo 'berkenaan dengan kebutuhan lingkungan saat ini dan di masa';
echo 'datang. Mengikuti perkembangan dan kemajuan teknologi terkini';
echo 'agar mampu menghadapi tantangan jaman dengan cara yang efektif';
echo 'dan efisien.';
echo '</p>';
echo '<a';
echo 'href="about.html"';
echo 'class="btn btn-primary py-sm-3 px-sm-5 rounded-pill mt-3"';
echo '>Read More</a';
echo '>';
echo '</div>';
echo '<div class="col-lg-6">';
echo '<img';
echo 'class="img-fluid wow zoomIn"';
echo 'data-wow-delay="0.5s"';
echo 'src="img/konsul-vector.jpg"';
echo 'style="border-radius: 1cm"';
echo '/>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- About End -->';
echo '';
echo '<!-- Service Start -->';
echo '<div class="container-xxl py-5">';
echo '<div class="container py-5 px-lg-5">';
echo '<div class="wow fadeInUp" data-wow-delay="0.1s">';
echo '<p class="section-title text-secondary justify-content-center">';
echo '<span></span>Our Services<span></span>';
echo '</p>';
echo '<h1 class="text-center mb-5">What Solutions We Provide</h1>';
echo '</div>';
echo '<div class="row g-4">';
echo '<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<div class="service-item d-flex flex-column text-center rounded">';
echo '<div class="service-icon flex-shrink-0">';
echo '<i class="fa fa-graduation-cap fa-2x"></i>';
echo '</div>';
echo '<h5 class="mb-3">Konseling Sekolah</h5>';
echo '<a class="btn btn-square" href="service.html"';
echo '><i class="fa fa-arrow-right"></i';
echo '></a>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">';
echo '<div class="service-item d-flex flex-column text-center rounded">';
echo '<div class="service-icon flex-shrink-0">';
echo '<i class="fa fa-briefcase fa-2x"></i>';
echo '</div>';
echo '<h5 class="mb-3">Konseling Karir</h5>';
echo '<a class="btn btn-square" href="service.html"';
echo '><i class="fa fa-arrow-right"></i';
echo '></a>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.5s">';
echo '<div class="service-item d-flex flex-column text-center rounded">';
echo '<div class="service-icon flex-shrink-0">';
echo '<i class="fa fa-user fa-2x"></i>';
echo '</div>';
echo '<h5 class="mb-3">Konseling Pribadi</h5>';
echo '<a class="btn btn-square" href="service.html"';
echo '><i class="fa fa-arrow-right"></i';
echo '></a>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<div class="service-item d-flex flex-column text-center rounded">';
echo '<div class="service-icon flex-shrink-0">';
echo '<i class="fa fa-users fa-2x"></i>';
echo '</div>';
echo '<h5 class="mb-3">Konseling Keluarga</h5>';
echo '<a class="btn btn-square" href="service.html"';
echo '><i class="fa fa-arrow-right"></i';
echo '></a>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">';
echo '<div class="service-item d-flex flex-column text-center rounded">';
echo '<div class="service-icon flex-shrink-0">';
echo '<i class="fa fa-thumbs-up fa-2x"></i>';
echo '</div>';
echo '<h5 class="mb-3">Pengembangan Organisasi</h5>';
echo '<a class="btn btn-square" href="service.html"';
echo '><i class="fa fa-arrow-right"></i';
echo '></a>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.5s">';
echo '<div class="service-item d-flex flex-column text-center rounded">';
echo '<div class="service-icon flex-shrink-0">';
echo '<i class="fa fa-search fa-2x"></i>';
echo '</div>';
echo '<h5 class="mb-3">Social Research</h5>';
echo '<a class="btn btn-square" href="service.html"';
echo '><i class="fa fa-arrow-right"></i';
echo '></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Service End -->';
echo '';
echo '<!-- Testimonial Start -->';
echo '<div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">';
echo '<div class="container py-5 px-lg-5">';
echo '<p class="section-title text-secondary justify-content-center">';
echo '<span></span>Testimonial<span></span>';
echo '</p>';
echo '<h1 class="text-center mb-5">What Say Our Clients!</h1>';
echo '<div class="owl-carousel testimonial-carousel">';
echo '<div class="testimonial-item bg-light rounded my-4">';
echo '<p class="fs-5">';
echo '<i class="fa fa-quote-left fa-4x text-primary mt-n4 me-3"></i';
echo '>Sejak tahun 2011 s.d sekarang perusahaan kami sudah menggunakan';
echo 'Jasa Pusat Layanan Psikologi Jayabaya untuk melaksanakan';
echo 'psikotes dan memberikan rekomendasi penerimaan calon karyawan.';
echo '</p>';
echo '<div class="d-flex align-items-center">';
echo '<img';
echo 'class="img-fluid flex-shrink-0 rounded-circle"';
echo 'src="img/testimonial-1.jpg"';
echo 'style="width: 65px; height: 65px"';
echo '/>';
echo '<div class="ps-4">';
echo '<h5 class="mb-1">Citra Publik Indonesia</h5>';
echo '<span>LSI Network</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="testimonial-item bg-light rounded my-4">';
echo '<p class="fs-5">';
echo '<i class="fa fa-quote-left fa-4x text-primary mt-n4 me-3"></i';
echo '>Pelayanan kami dalam membimbing anak bersifat khas dan sangat';
echo 'personal, masing-masing anak mempunyai waktu personal untuk';
echo 'sharing dan konsultasi dengan konselor.';
echo '</p>';
echo '<div class="d-flex align-items-center">';
echo '<img';
echo 'class="img-fluid flex-shrink-0 rounded-circle"';
echo 'src="img/testimonial-2.jpg"';
echo 'style="width: 65px; height: 65px"';
echo '/>';
echo '<div class="ps-4">';
echo '<h5 class="mb-1">Principal Pulo Mas Campus Global Sevilla</h5>';
echo '<span>Campus Global Sevilla</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="testimonial-item bg-light rounded my-4">';
echo '<p class="fs-5">';
echo '<i class="fa fa-quote-left fa-4x text-primary mt-n4 me-3"></i';
echo '>Sangat membantu saya untuk menemukan solusi-solusi yang ada';
echo 'dalam setiap topik yang saya tulis, dan juga memberikan ruang';
echo 'yang nyaman untuk saya menceritakan permasalahan diri.';
echo '</p>';
echo '<div class="d-flex align-items-center">';
echo '<img';
echo 'class="img-fluid flex-shrink-0 rounded-circle"';
echo 'src="img/testimonial-3.jpg"';
echo 'style="width: 65px; height: 65px"';
echo '/>';
echo '<div class="ps-4">';
echo '<h5 class="mb-1">Putra Wahyu Prartama</h5>';
echo '<span>Mahasiswa</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Testimonial End -->';
echo '';
echo '<!-- Team Start -->';
echo '<div class="container-xxl py-5">';
echo '<div class="container py-5 px-lg-5">';
echo '<div class="wow fadeInUp" data-wow-delay="0.1s">';
echo '<p class="section-title text-secondary justify-content-center">';
echo '<span></span>Our Team<span></span>';
echo '</p>';
echo '<h1 class="text-center mb-5">Our Team Members</h1>';
echo '</div>';
echo '<div class="row g-4">';
echo '<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<div class="team-item bg-light rounded">';
echo '<div class="text-center border-bottom p-4">';
echo '<img';
echo 'class="img-fluid rounded-circle mb-4"';
echo 'src="img/team-1.jpg"';
echo 'alt=""';
echo '/>';
echo '<h5>Dr. Widura Imam Mustopo, M.Si., Psikolog</h5>';
echo '<span>Psikolog</span>';
echo '</div>';
echo '<div class="d-flex justify-content-center p-4">';
echo '<a class="btn btn-square mx-1" href=""';
echo '><i class="fab fa-facebook-f"></i';
echo '></a>';
echo '<a class="btn btn-square mx-1" href=""';
echo '><i class="fab fa-twitter"></i';
echo '></a>';
echo '<a class="btn btn-square mx-1" href=""';
echo '><i class="fab fa-instagram"></i';
echo '></a>';
echo '<a class="btn btn-square mx-1" href=""';
echo '><i class="fab fa-linkedin-in"></i';
echo '></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">';
echo '<div class="team-item bg-light rounded">';
echo '<div class="text-center border-bottom p-4">';
echo '<img';
echo 'class="img-fluid rounded-circle mb-4"';
echo 'src="img/team-2.jpg"';
echo 'alt=""';
echo '/>';
echo '<h5>Dra. Sri Mulyani Nasution, M. Psi., Psikolog</h5>';
echo '<span>Psikolog</span>';
echo '</div>';
echo '<div class="d-flex justify-content-center p-4">';
echo '<a class="btn btn-square mx-1" href=""';
echo '><i class="fab fa-facebook-f"></i';
echo '></a>';
echo '<a class="btn btn-square mx-1" href=""';
echo '><i class="fab fa-twitter"></i';
echo '></a>';
echo '<a class="btn btn-square mx-1" href=""';
echo '><i class="fab fa-instagram"></i';
echo '></a>';
echo '<a class="btn btn-square mx-1" href=""';
echo '><i class="fab fa-linkedin-in"></i';
echo '></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.5s">';
echo '<div class="team-item bg-light rounded">';
echo '<div class="text-center border-bottom p-4">';
echo '<img';
echo 'class="img-fluid rounded-circle mb-4"';
echo 'src="img/team-3.jpg"';
echo 'alt=""';
echo '/>';
echo '<h5>Engkin Zainal Muttaqin, S,Psi., M.Psi., Psikolog</h5>';
echo '<span>Psikolog</span>';
echo '</div>';
echo '<div class="d-flex justify-content-center p-4">';
echo '<a class="btn btn-square mx-1" href=""';
echo '><i class="fab fa-facebook-f"></i';
echo '></a>';
echo '<a class="btn btn-square mx-1" href=""';
echo '><i class="fab fa-twitter"></i';
echo '></a>';
echo '<a class="btn btn-square mx-1" href=""';
echo '><i class="fab fa-instagram"></i';
echo '></a>';
echo '<a class="btn btn-square mx-1" href=""';
echo '><i class="fab fa-linkedin-in"></i';
echo '></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Team End -->';
echo '';
echo '<!-- Footer Start -->';
echo '<div';
echo 'class="container-fluid bg-primary text-light footer wow fadeIn"';
echo 'data-wow-delay="0.1s"';
echo '>';
echo '<div class="container py-5 px-lg-5">';
echo '<div class="row g-5">';
echo '<div class="col-md-6 col-lg-3">';
echo '<p class="section-title text-white h5 mb-4">';
echo 'Address<span></span>';
echo '</p>';
echo '<p>';
echo '<i class="fa fa-map-marker-alt me-3"></i>Jl. Pulomas Selatan';
echo 'Kav. 23 Jakarta 13210';
echo '</p>';
echo '<p><i class="fa fa-phone-alt me-3"></i>+62 878-6878-5933</p>';
echo '<p><i class="fa fa-envelope me-3"></i>plpjayabaya@gmail.com</p>';
echo '<div class="d-flex pt-2">';
echo '<a class="btn btn-outline-light btn-social" href=""';
echo '><i class="fab fa-twitter"></i';
echo '></a>';
echo '<a class="btn btn-outline-light btn-social" href=""';
echo '><i class="fab fa-facebook-f"></i';
echo '></a>';
echo '<a class="btn btn-outline-light btn-social" href=""';
echo '><i class="fab fa-instagram"></i';
echo '></a>';
echo '<a class="btn btn-outline-light btn-social" href=""';
echo '><i class="fab fa-linkedin-in"></i';
echo '></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Footer End -->';
echo '';
echo '<!-- Back to Top -->';
echo '<a href="#" class="btn btn-lg btn-secondary btn-lg-square back-to-top"';
echo '><i class="bi bi-arrow-up"></i';
echo '></a>';
echo '</div>';
echo '';
echo '<!-- JavaScript Libraries -->';
echo '<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>';
echo '<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>';
echo '<script src="lib/wow/wow.min.js"></script>';
echo '<script src="lib/easing/easing.min.js"></script>';
echo '<script src="lib/waypoints/waypoints.min.js"></script>';
echo '<script src="lib/counterup/counterup.min.js"></script>';
echo '<script src="lib/owlcarousel/owl.carousel.min.js"></script>';
echo '<script src="lib/isotope/isotope.pkgd.min.js"></script>';
echo '<script src="lib/lightbox/js/lightbox.min.js"></script>';
echo '';
echo '<!-- Template Javascript -->';
echo '<script src="js/main.js"></script>';
echo '</body>';
echo '</html>';
echo '';
?>